spring:
  application:
    name: demo client
  boot:
    admin:
      client:
        url: http://localhost:9999
        management:
          endpoints:
            health:
              show-details: "always"

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      enabled: true
      mode: FULL


auth:
  service:
    unprotectedpath:
      - /actuator/**
      - actuator/**

